#!/bin/bash -l

# Request 2 cores. This will set NSLOTS=2
#$ -pe omp 2

# Request 1 GPU
#$ -l gpus=0.5

# Request at least compute capability 3.5
# K40 GPUs have compute capability 3.5
# P100 GPUs - 6.0
# V100 GPUS - 7.0
#$ -l gpu_c=3.5

# Give the job a name
#$ -N cnn

# Send email when the job is done
#$ -m e

#Load modules
module load python/3.6.2
module load tensorflow/r1.10

#Run python script
python3 robust_cw2_mnist.py


